// GitHub Pages 전용: 브라우저에서 바로 Supabase를 사용한다.
// 비밀 키는 절대 브라우저에 넣지 않으며, 공개용 anon key 만 사용하고
// Supabase Auth 또는 RLS 정책으로 접근을 제어한다.
const URL=window.SUPABASE_URL, KEY=window.SUPABASE_ANON_KEY, KINDS=['recipes','batches','notes'], TEAM='main', App=window.TofuApp;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={status:'loading',user:null,error:'',rows:{},lastSync:null}; let sb, channel, synced={};
const clean=x=>{const y={...x};Object.keys(y).forEach(k=>{if(k.startsWith('_')||k==='builtin'||y[k]===undefined)delete y[k]});return y};
const sig=x=>JSON.stringify(clean(x)); const items=(s,k)=>k==='recipes'?s.recipes.filter(x=>!x.builtin):s[k]||[];
function pill(){const p=$('#cloud-pill');if(!p)return;p.hidden=S.status==='off';p.textContent=S.status==='member'?'☁️ 동기화됨':({loading:'☁️ 연결 중…',signedout:'☁️ 로그인',error:'⚠️ 오류'}[S.status]||'☁️');p.className='cloud-pill '+(S.status==='member'?'ok':'warn')}
function render(){pill();const b=$('#cloud-panel');if(!b)return;if(S.status==='off')b.innerHTML='<p class="muted">Supabase 설정이 없습니다.</p>';else if(S.status==='loading')b.innerHTML='<p class="muted">Supabase 연결 중…</p>';else if(S.status==='signedout')b.innerHTML='<p>Supabase 계정으로 로그인하세요.</p><button class="btn" id="cl-login">로그인</button> <button class="btn ghost" id="cl-signup">회원가입</button>';else if(S.status==='error')b.innerHTML=`<p class="cloud-err">⚠️ ${esc(S.error)}</p><button class="btn ghost" id="cl-login">다시 로그인</button>`;else b.innerHTML=`<p>☁️ ${esc(S.user?.email)} · 실시간 동기화됨</p><button class="btn ghost small" id="cl-logout">로그아웃</button>`;$('#cl-login')?.addEventListener('click',login);$('#cl-signup')?.addEventListener('click',signup);$('#cl-logout')?.addEventListener('click',()=>sb.auth.signOut())}
async function load(){const local=App.getState();const {data,error}=await sb.from('tofu_records').select('*').eq('team_id',TEAM);if(error)throw error;for(const k of KINDS){const remote=(data||[]).filter(x=>x.kind===k).map(x=>({...x.data,id:x.id}));const have=new Set(remote.map(x=>x.id));const localOnly=items(local,k).filter(x=>!have.has(x.id));S.rows[k]=[...remote,...localOnly];synced[k]=new Map(remote.map(x=>[x.id,sig(x)]));App.applyRemote(k,S.rows[k])}await push(App.getState());S.lastSync=new Date()}
async function push(state){if(S.status!=='member')return;try{for(const k of KINDS){const cur=new Map(items(state,k).map(x=>[x.id,x])),old=synced[k]||new Map();for(const [id,row]of cur)if(old.get(id)!==sig(row)){const {error}=await sb.from('tofu_records').upsert({team_id:TEAM,kind:k,id,data:clean(row),updated_by:S.user.email,updated_at:new Date().toISOString()},{onConflict:'team_id,kind,id'});if(error)throw error;old.set(id,sig(row))}for(const id of old.keys())if(!cur.has(id)){const {error}=await sb.from('tofu_records').delete().match({team_id:TEAM,kind:k,id});if(error)throw error;old.delete(id)}}S.lastSync=new Date();render()}catch(e){S.status='error';S.error='Supabase 저장 실패: '+(e.message||e);render();throw e}}
function subscribe(){channel=sb.channel('tofu-records').on('postgres_changes',{event:'*',schema:'public',table:'tofu_records',filter:'team_id=eq.main'},p=>{const k=(p.new||p.old).kind;if(p.eventType==='DELETE')S.rows[k]=(S.rows[k]||[]).filter(x=>x.id!==p.old.id);else{const r={...p.new.data,id:p.new.id};S.rows[k]=[...(S.rows[k]||[]).filter(x=>x.id!==r.id),r];synced[k].set(r.id,sig(r))}App.applyRemote(k,S.rows[k]||[]);render()}).subscribe()}
async function signed(user){S.user=user;if(!user){S.status='signedout';render();return}try{S.status='member';await load();subscribe()}catch(e){S.status='error';S.error=e.message||String(e)}render()}
async function login(){const email=prompt('Supabase 계정 이메일');const password=prompt('비밀번호');if(!email||!password)return;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){S.status='error';S.error=error.message;render();return}signed(data.user)}
async function signup(){const email=prompt('가입할 이메일'),password=prompt('비밀번호(6자 이상)');if(!email||!password)return;const {error}=await sb.auth.signUp({email,password});S.status='signedout';S.error=error?.message||'가입 완료. 이메일 인증 후 로그인하세요.';render()}
window.TofuSync={push,get connected(){return S.status==='member'}};
if(!URL||!KEY){S.status='off';render()}else import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm').then(({createClient})=>{sb=createClient(URL,KEY);sb.auth.getSession().then(x=>signed(x.data.session?.user));sb.auth.onAuthStateChange((_e,s)=>{if(!s)signed(null)})}).catch(e=>{S.status='error';S.error=e.message;render()});
